import {getStore} from '@netlify/blobs';
const escape=(value:any)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export default async(req:Request,context:any)=>{
 const token=context.params.token;
 if(req.method!=='GET'||!/^\w{8}-\w{4}-4\w{3}-[89ab]\w{3}-\w{12}$/i.test(token||''))return new Response('Introuvable',{status:404});
 try{
 const order:any=await getStore({name:'paypal-invoices',consistency:'strong'}).get('enterprise-'+token,{type:'json'});
 if(!order)return new Response('Introuvable',{status:404});
 const rows=[['Entreprise',order.company],['Contact',order.contactName],['Email',order.email],['Adresse entreprise',order.companyAddress],['Téléphone',order.phone],['Site',order.website],['Livraison',order.shippingAddress+', '+order.shippingPostal+' '+order.shippingCity],['Date souhaitée',order.deliveryDate],['Référence',order.ref],['Article',order.productName],['Couleur',order.colour],['Parfum',order.fragrance],['Quantité',order.quantity],['Prénoms personnalisés',order.personalized?'Oui (+1,50 CHF / pièce)':'Non'],['Sac cadeau',order.bag?'Oui (+2,00 CHF / pièce)':'Non'],['Emplacement des coordonnées',order.placement],['Taille du logo',(order.logoScale||65)+' % de la zone du sac'],['Position du logo',(order.logoX??37)+' % horizontal, '+(order.logoY??61)+' % vertical'],['Message',order.message],['Prix unitaire',order.items?'Voir les articles ci-dessous':'CHF '+(order.unitCents/100).toFixed(2)],['Total devis','CHF '+(order.totalCents/100).toFixed(2)]];
 const articles=order.items?'<h2>Articles du devis</h2>'+order.items.map((item:any)=>'<section><h3>'+escape(item.ref+' — '+item.productName)+'</h3><p>'+escape(item.quantity+' × CHF '+(item.unitCents/100).toFixed(2)+' · '+item.colour+' · '+item.fragrance)+'</p><p>'+escape(item.message)+'</p><p>'+escape('Sac : '+(item.bag?'oui':'non')+' · Personnalisation : '+item.placement+' · Taille du logo : '+(item.logoScale||65)+' % · Position : '+(item.logoX??37)+' %, '+(item.logoY??61)+' %')+'</p><p>'+escape(item.names.join(', '))+'</p><b>'+escape('Total article : CHF '+(item.totalCents/100).toFixed(2))+'</b></section>').join(''):'';
 const html='<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Commande entreprise — '+escape(order.ref)+'</title><style>body{font:16px system-ui;max-width:800px;margin:30px auto;padding:20px}table{width:100%;border-collapse:collapse}td{padding:8px;border-bottom:1px solid #ddd;white-space:pre-wrap}img{max-width:250px;max-height:200px}li{padding:4px}@media print{a,button{display:none}}</style><h1>Fiche de personnalisation</h1><p>Facture '+escape(order.invoiceNumber||'en cours de création')+'. Vérifiez le paiement dans PayPal avant de préparer la commande.</p>'+(order.invoiceUrl?'<p><a href="'+escape(order.invoiceUrl)+'" rel="noreferrer">Consulter la facture PayPal</a></p>':'')+'<table>'+rows.map(([label,value])=>'<tr><td>'+escape(label)+'</td><td>'+escape(value)+'</td></tr>').join('')+'</table>'+articles+(!order.items&&order.names.length?'<h2>Prénoms</h2><ol>'+order.names.map((name:string)=>'<li>'+escape(name)+'</li>').join('')+'</ol>':'')+(order.logo?'<h2>Logo fourni</h2><img alt="Logo entreprise" src="'+escape(order.logo)+'">':'')+'</html>';
 return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Robots-Tag':'noindex, nofollow','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; img-src data:; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'"}});
 }catch{return new Response('Indisponible',{status:503});}
};
export const config={path:'/api/enterprise-order/:token',rateLimit:{windowLimit:30,windowSize:60,aggregateBy:['ip','domain']}};
